FROM node:alpine as deps

WORKDIR /frontend

COPY package.json package-lock.json ./

RUN npm install --force

FROM node:alpine as builder

WORKDIR /frontend

COPY . .
COPY --from=deps /frontend/node_modules ./node_modules