FROM node:alpine as deps

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --force

FROM node:alpine as builder

WORKDIR /app

COPY . .
COPY --from=deps /app/node_modules ./node_modules

RUN npm run build

EXPOSE 3000

CMD [ "npm" , "run" , "dev" ]